# Generated by Django 3.1.7 on 2021-07-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_actividad', models.CharField(max_length=100)),
                ('grafico', models.CharField(max_length=800)),
            ],
        ),
    ]
