# Generated by Django 3.2.5 on 2021-08-02 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('idlaternativa', models.IntegerField(primary_key=True, serialize=False)),
                ('txt_alte', models.CharField(db_collation='utf8_unicode_ci', max_length=225)),
            ],
            options={
                'db_table': 'alternativa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id_ambiente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ambiente', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ambiente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aprueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idimagen', models.IntegerField()),
                ('fecha_aprueba', models.DateTimeField()),
                ('justificacion', models.CharField(max_length=225)),
                ('esaprobado', models.IntegerField()),
            ],
            options={
                'db_table': 'aprueba',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsignaReimAlumno',
            fields=[
                ('sesion_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('datetime_inicio', models.DateTimeField()),
                ('datetime_termino', models.DateTimeField()),
            ],
            options={
                'db_table': 'asigna_reim_alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogoReim',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('datetime_realiza', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalogo_reim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fono', models.CharField(blank=True, max_length=255, null=True)),
                ('rbd', models.IntegerField(blank=True, null=True, unique=True)),
                ('dgv_rbd', models.IntegerField(blank=True, null=True)),
                ('mrun', models.IntegerField(blank=True, null=True)),
                ('rut_sostenedor', models.IntegerField(blank=True, null=True)),
                ('p_juridica', models.IntegerField(blank=True, null=True)),
                ('rural', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'colegio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_personal', models.CharField(max_length=120)),
                ('opciones_inicio', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'detalle_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DibujoReim',
            fields=[
                ('id_dibujo_reim', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.TextField()),
            ],
            options={
                'db_table': 'dibujo_reim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eje',
            fields=[
                ('id_eje', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'eje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'elemento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('update_link', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'FECHA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Forma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'forma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('idimagen', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('imagen', models.TextField()),
            ],
            options={
                'db_table': 'imagen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarioReim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('datetime_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'inventario_reim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('iditem', models.IntegerField(db_column='IdItem', primary_key=True, serialize=False)),
                ('pregunta', models.CharField(db_collation='utf8_unicode_ci', db_column='Pregunta', max_length=255)),
                ('justificacion', models.CharField(blank=True, db_column='Justificacion', max_length=255, null=True)),
                ('dificultad', models.IntegerField(blank=True, db_column='Dificultad', null=True)),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemAlt',
            fields=[
                ('indice', models.IntegerField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('escorrecto', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'item_alt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Letra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'letra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'nivel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjetivoAprendizaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('eje_id', models.IntegerField()),
            ],
            options={
                'db_table': 'objetivo_aprendizaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Opinionxdibujo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_insert', models.DateTimeField()),
                ('opinion', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'opinionxdibujo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pertenece',
            fields=[
                ('fecha', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pertenece',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reaccion',
            fields=[
                ('idreaccion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrereaccion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'reaccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reaccionxdibujo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'reaccionxdibujo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion_educativa', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'reim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubEje',
            fields=[
                ('id_sub_eje', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'sub_eje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiempoxactividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('final', models.DateTimeField(blank=True, null=True)),
                ('causa', models.IntegerField()),
            ],
            options={
                'db_table': 'tiempoxactividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id_ulearnet', models.IntegerField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'URL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=255, null=True)),
                ('rut', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('alumno', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActividadOa',
            fields=[
                ('id_oa', models.OneToOneField(db_column='id_oa', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pages.objetivoaprendizaje')),
            ],
            options={
                'db_table': 'actividad_oa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Actividadxreim',
            fields=[
                ('id_actividad', models.OneToOneField(db_column='id_actividad', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pages.actividad')),
            ],
            options={
                'db_table': 'actividadxreim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlumnoRespuestaActividad',
            fields=[
                ('id_per', models.OneToOneField(db_column='id_per', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pages.periodo')),
                ('datetime_touch', models.DateTimeField()),
                ('eje_x', models.FloatField(db_column='Eje_X')),
                ('eje_y', models.FloatField(db_column='Eje_Y')),
                ('eje_z', models.FloatField(db_column='Eje_Z')),
                ('correcta', models.IntegerField()),
                ('resultado', models.CharField(max_length=225)),
                ('tipo_registro', models.IntegerField(db_column='Tipo_Registro')),
            ],
            options={
                'db_table': 'alumno_respuesta_actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsignaReim',
            fields=[
                ('letra', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pages.letra')),
            ],
            options={
                'db_table': 'asigna_reim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AvatarSesion',
            fields=[
                ('elemento', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pages.elemento')),
            ],
            options={
                'db_table': 'Avatar-Sesion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleElemento',
            fields=[
                ('id_elemento', models.OneToOneField(db_column='id_elemento', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pages.elemento')),
                ('descripcion', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'detalle_elemento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElemAct',
            fields=[
                ('elemento', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pages.elemento')),
            ],
            options={
                'db_table': 'Elem-Act',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElemReim',
            fields=[
                ('elemento', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pages.elemento')),
            ],
            options={
                'db_table': 'Elem-REIM',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReimAmbiente',
            fields=[
                ('reim', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pages.reim')),
            ],
            options={
                'db_table': 'REIM-Ambiente',
                'managed': False,
            },
        ),
    ]
