# Generated by Django 3.2.5 on 2021-08-12 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graficoxactividad',
            fields=[
                ('id_actividad', models.OneToOneField(db_column='id_actividad', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pages.actividad')),
                ('embedurl', models.CharField(db_column='embedUrl', max_length=45)),
            ],
            options={
                'db_table': 'graficoxactividad',
                'managed': False,
            },
        ),
    ]
