# Generated by Django 3.2.5 on 2022-01-05 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_graficoxactividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionPropuesta',
            fields=[
                ('id_elemento', models.OneToOneField(db_column='id_elemento', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pages.elemento')),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_evaluacion', models.DateTimeField(blank=True, null=True)),
                ('evaluacion', models.CharField(blank=True, max_length=255, null=True)),
                ('propuesta', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'evaluacion_propuesta',
                'managed': False,
            },
        ),
    ]
